# https://docs.docker.com/engine/swarm/stack-deploy/
# $ ./gradlew deployDockerStack
version: '3.9'

services:
  orchestrator:
    image: 127.0.0.1:6000/save-orchestrator
    ports:
      - "5100:5100"
    volumes:
      - "/var/run/docker.sock:/var/run/docker.sock"
    labels:
      - prometheus-job
  backend:
    image: 127.0.0.1:6000/save-backend
    ports:
      - "5000:5000"
    labels:
      - prometheus-job
  prometheus:
    image: prom/prometheus
    ports:
      - "9090:9090"
    volumes:
      - "~/configs/prometheus.yml:/etc/prometheus/prometheus.yml"
  grafana:
    image: grafana/grafana
    ports:
      - "9100:3000"
