# https://docs.docker.com/engine/swarm/stack-deploy/
# $ docker-compose build
# $ docker-compose push
# $ docker stack deploy --compose-file save-stack.yml save
version: '3.9'

services:
  registry:
    # a throwaway registry used to distribute images in a swarm
    image: registry:2
    ports:
      - "5000:5000"
  orchestrator:
    # todo: set version from gradle?
    image: 127.0.0.1:5000/save-orchestrator
    build: save-orchestrator  # location of Dockerfile?
    ports:
      - "5100:5100"
  backend:
    # todo: set version from gradle?
    image: 127.0.0.1:5000/save-backend
    build: save-backend
    ports:
      - "5000:5000"
  prometheus:
    image: prom/prometheus
    ports:
      - "9090:9090"
    volumes:
      - "/path/to/prometheus.yml:/etc/prometheus/prometheus.yml"
  grafana:
    image: grafana/grafana
    ports:
      - "9100:3000"