apiVersion: networking.k8s.io/v1
kind: NetworkPolicy
metadata:
  name: agent-network-policy-orchestrator
  namespace: {{ .Values.agentNamespace }}
spec:
  # Should be applied to save-agents only
  #
  # As for now, there is no way to tell orchestrator pod from sandbox pod so need to allow connection to both
  # orchestrator and sandbox.
  podSelector:
    matchLabels:
      io.kompose.service: save-agent
  policyTypes:
    - Egress
  egress:
    - to:
        # Allow traffic to save-orchestrator
        - namespaceSelector:
            matchLabels:
              name: save-cloud
        - podSelector:
            matchLabels:
              io.kompose.service: orchestrator
      ports:
        - protocol: TCP
          port: {{ .Values.orchestrator.containerPort }}
    - to:
        # Allow traffic to save-sandbox
        - namespaceSelector:
            matchLabels:
              name: save-cloud
        - podSelector:
            matchLabels:
              io.kompose.service: sandbox
      ports:
        - protocol: TCP
          port: {{ .Values.sandbox.containerPort }}