{{ if .Values.agentNamespace }}
# Namespace config for agent service
apiVersion: v1
kind: Namespace
metadata:
  name: {{ .Values.agentNamespace }}
---
#agent services
apiVersion: v1
kind: Service
metadata:
  name: {{ .Values.backend_cosv.name }}
  namespace: {{ .Values.agentNamespace }}
spec:
  type: ExternalName
  externalName: {{ .Values.backend_cosv.name }}.{{ .Values.namespace }}.svc.cluster.local
  ports:
    - port: {{ .Values.backend_cosv.containerPort }}
---
apiVersion: v1
kind: Service
metadata:
  name: {{ .Values.backend.name }}
  namespace: {{ .Values.agentNamespace }}
spec:
  type: ExternalName
  externalName: {{ .Values.backend.name }}.{{ .Values.namespace }}.svc.cluster.local
  ports:
    - port: {{ .Values.backend.containerPort }}
---
apiVersion: v1
kind: Service
metadata:
  name: {{ .Values.orchestrator.name }}
  namespace: {{ .Values.agentNamespace }}
spec:
  type: ExternalName
  externalName: {{ .Values.orchestrator.name }}.{{ .Values.namespace }}.svc.cluster.local
  ports:
    - port: {{ .Values.orchestrator.containerPort }}
---
apiVersion: v1
kind: Service
metadata:
  name: {{ .Values.demo.name }}
  namespace: {{ .Values.agentNamespace }}
spec:
  type: ExternalName
  externalName: {{ .Values.demo.name }}.{{ .Values.namespace }}.svc.cluster.local
  ports:
    - port: {{ .Values.demo.containerPort }}
---
# General network policy for agent service
apiVersion: networking.k8s.io/v1
kind: NetworkPolicy
metadata:
  name: agent-network-policy-general
  namespace: {{ .Values.agentNamespace }}
spec:
  # Should be applied to all pods in namespace
  podSelector: {}
  policyTypes:
    - Egress
  egress:
    - to:
        # https://stackoverflow.com/q/73049535
        - ipBlock:
            cidr: 0.0.0.0/0
            # Forbid private IP ranges effectively allowing only egress to the Internet
            except:
              - 10.0.0.0/8
              - 172.16.0.0/12
              - 192.168.0.0/16
    - to:
        # Allow traffic to kubernetes DNS service
        - namespaceSelector:
            matchLabels:
              kubernetes.io/metadata.name: "kube-system"
        - podSelector:
            matchLabels:
              k8s-app: "kube-dns"

---
# agent network policy for services
apiVersion: networking.k8s.io/v1
kind: NetworkPolicy
metadata:
  name: agent-network-policy-services
  namespace: {{ .Values.agentNamespace }}
spec:
  # Should be applied to save-agents only
  #
  # As for now, there is no way to tell orchestrator pod so need to allow connection to orchestrator.
  podSelector:
    matchLabels:
      io.kompose.service: save-agent
  policyTypes:
    - Egress
  egress:
    - to:
        # Allow traffic to save-orchestrator
        - namespaceSelector:
            matchLabels:
              name: {{ .Values.namespace }}
        - podSelector:
            matchLabels:
              io.kompose.service: orchestrator
      ports:
        - protocol: TCP
          port: {{ .Values.orchestrator.containerPort }}
    - to:
        # Allow traffic to save-backend
        - namespaceSelector:
            matchLabels:
              name: {{ .Values.namespace }}
        - podSelector:
            matchLabels:
              io.kompose.service: backend
      ports:
        - protocol: TCP
          port: {{ .Values.backend.containerPort }}
    - to:
        # Allow traffic to save-backend-cosv
        - namespaceSelector:
            matchLabels:
              name: {{ .Values.namespace }}
        - podSelector:
            matchLabels:
              io.kompose.service: backend-cosv
      ports:
        - protocol: TCP
          port: {{ .Values.backend_cosv.containerPort }}
    - to:
        # Allow traffic to save-demo
        - namespaceSelector:
            matchLabels:
              name: {{ .Values.namespace }}
        - podSelector:
            matchLabels:
              io.kompose.service: demo
      ports:
        - protocol: TCP
          port: {{ .Values.demo.containerPort }}
{{ end }}