apiVersion: networking.k8s.io/v1
kind: NetworkPolicy
metadata:
  name: agent-network-policy-general
  namespace: {{ .Values.agentNamespace }}
spec:
  # Should be applied to all pods in namespace
  podSelector: {}
  policyTypes:
    - Egress
  egress:
    - to:
        # https://stackoverflow.com/q/73049535
        - ipBlock:
            cidr: 0.0.0.0/0
            # Forbid private IP ranges effectively allowing only egress to the Internet
            except:
              - 10.0.0.0/8
              - 172.16.0.0/12
              - 192.168.0.0/16
    - to:
        # Allow traffic to kubernetes DNS service
        - namespaceSelector:
            matchLabels:
              kubernetes.io/metadata.name: "kube-system"
        - podSelector:
            matchLabels:
              k8s-app: "kube-dns"
