apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ .Values.backend.name }}-config
data:
  application.properties: |
    backend.preprocessorUrl=http://preprocessor:5200
    server.shutdown=graceful
    management.endpoints.web.exposure.include=*
