apiVersion: apps/v1
kind: Deployment
metadata:
  name: backend
  labels:
    {{- include "common.labels" (merge (dict "service" .Values.backend) .) | nindent 4 }}
spec:
  selector:
    matchLabels:
      io.kompose.service: backend
  template:
    metadata:
      labels:
        io.kompose.service: backend
    spec:
      restartPolicy: Always
      {{- include "spring-boot.securityContext" | indent 6 }}
      containers:
        - name: backend
          {{- include "spring-boot.common" (merge (dict "service" .Values.backend) .) | nindent 10 }}
          volumeMounts:
            - {{ include "spring-boot.config-volume-mount" . | indent 14 | trim }}
            - name: fs-storage
              mountPath: /home/cnb/files
            # https://github.com/kubernetes/kubernetes/issues/65835#issuecomment-411399356
            # should un-hardcode path to secrets from env postprocessor
            - name: database-secret
              mountPath: /run/secrets/db_url
              subPath: db_url
            - name: database-secret
              mountPath: /run/secrets/db_username
              subPath: db_username
            - name: database-secret
              mountPath: /run/secrets/db_password
              subPath: db_password
          {{- include "spring-boot.management" .Values.backend | nindent 10 }}
      volumes:
        - {{ include "spring-boot.config-volume" (dict "service" .Values.backend) | indent 10 | trim }}
        - name: fs-storage
          persistentVolumeClaim:
            claimName: save-fs-storage
        - name: database-secret
          secret:
            secretName: db-secrets
