apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ .Values.backend.name }}-config
data:
  application.properties: |
    backend.preprocessor-url=http://preprocessor
    backend.orchestrator-url=http://orchestrator
    server.shutdown=graceful
    management.endpoints.web.exposure.include=*
