apiVersion: v1
kind: Endpoints
metadata:
  name: mysql-service
subsets:
  - addresses:
      - ip: {{ .Values.mysql.ip }}
    ports:
      - port: 3306

---

apiVersion: v1
kind: Service
metadata:
  name: mysql-service
spec:
  ports:
    - port: 3306
      targetPort: 3306
      protocol: TCP
  selector: {}
  type: ClusterIP
