apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ .Values.demo.name }}-config
data:
  application.properties: |
    management.endpoints.web.exposure.include=*
    management.server.port={{ .Values.demo.managementPort }}
