apiVersion: v1
kind: ServiceAccount
metadata:
  name: demo-sa

---

apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: demo-jobs-binding
  {{ if .Values.agentNamespace }}
  namespace: {{ .Values.agentNamespace }}
  {{ end }}
subjects:
  - kind: ServiceAccount
    name: demo-sa
    namespace: {{ .Values.namespace }}
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: jobs-executor
