apiVersion: apps/v1
kind: Deployment
metadata:
  name: demo-cpg
  labels:
    {{- include "common.labels" (merge (dict "service" .Values.demo_cpg) .) | nindent 4 }}
spec:
  selector:
    matchLabels:
      io.kompose.service: demo-cpg
  strategy:
    # Because of shared volume with multi-attach problem
    type: Recreate
  template:
    metadata:
      labels:
        {{- include "pod.common.labels" (merge (dict "service" .Values.demo_cpg ) .) | nindent 8 }}
      annotations:
        {{- include "pod.common.annotations" (dict "service" .Values.demo_cpg ) | nindent 8 }}
    spec:
      restartPolicy: Always
      {{- include "cnb.securityContext" . | nindent 6 }}
      containers:
        - name: demo-cpg
          # FixMe: set correct command when building image
          command: ["/cnb/process/executable-jar"]
          {{- include "spring-boot.common" (merge (dict "service" .Values.demo_cpg) .) | nindent 10 }}
          env:
            {{- include "spring-boot.common.env" (merge (dict "service" .Values.demo_cpg) .) | nindent 12 }}
            - name: JAVA_TOOL_OPTIONS
              value: -XX:ReservedCodeCacheSize=48M
            - name: CLASSPATH
              value: /workspace/BOOT-INF/lib/*:.
          volumeMounts:
            - {{ include "spring-boot.config-volume-mount" . | indent 14 | trim }}
          {{- include "spring-boot.management" .Values.demo_cpg | nindent 10 }}
          resources:
            limits:
              memory: 500M
            requests:
              memory: 300M
      volumes:
        - {{ include "spring-boot.config-volume" (dict "service" .Values.demo_cpg) | indent 10 | trim }}
---
apiVersion: v1
kind: Service
metadata:
{{- include "service.common.metadata" (dict "service" .Values.demo_cpg) | nindent 2 }}
spec:
  {{ if .Values.demo_cpg.clusterIP }}
  clusterIP: {{ .Values.demo_cpg.clusterIP }}
  {{ end }}
  ports:
    {{- include "service.common.ports" (dict "service" .Values.demo_cpg) | nindent 4 }}
  selector:
    {{- include "service.common.selectors" (dict "service" .Values.demo_cpg) | nindent 4 }}
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ .Values.demo_cpg.name }}-config
data:
  application.properties: |
    {{ if .Values.demo_cpg.applicationProperties }}
    {{- .Values.demo_cpg.applicationProperties | nindent 4 }}
    {{ end }}
