apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ .Values.demo.name }}-config
data:
  application.properties: |
    {{ if .Values.demo.applicationProperties }}
    {{- .Values.demo.applicationProperties | nindent 4 }}
    {{ end }}
