apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ .Values.demo.name }}-config
data:
  application.properties: |
    demo.kubernetes.apiServerUrl=http://kubernetes.default.svc
    demo.kubernetes.serviceAccount=${POD_SERVICE_ACCOUNT}
    demo.kubernetes.namespace=${POD_NAMESPACE}

    management.endpoints.web.exposure.include=*
    management.server.port={{ .Values.demo.managementPort }}
    logging.level.org.springframework=DEBUG
    spring.datasource.url=${spring.datasource.demo-url}

    {{ if .Values.demo.applicationProperties }}
    {{- .Values.demo.applicationProperties | nindent 4 }}
    {{ end }}

    demo.backend-url=http://backend/internal
    demo.agent-config.demo-url=http://demo
    demo.s3-storage.endpoint=http://s3
