apiVersion: v1
kind: ServiceAccount
metadata:
  name: demo-sa

---

apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: jobs-demo-executor
rules:
  - apiGroups: [batch]
    resources: [jobs]
    verbs: ["get", "list", "watch", "create", "update", "patch", "delete"]
  - apiGroups: [""]
    resources: [pods]
    verbs: [list, get, delete, create]
  - apiGroups: [""]
    resources: [pods/portforward]
    verbs: ["*"]
  - apiGroups: [""]
    resources: [configmaps, secrets]
    verbs: [list, get, watch]

---

apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: demo-jobs-binding
subjects:
  - kind: ServiceAccount
    name: demo-sa
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: jobs-demo-executor
