apiVersion: v1
kind: Service
metadata:
{{- include "service.common.metadata" (dict "service" .Values.frontend) | nindent 2 }}
spec:
  ports:
    {{- include "service.common.ports" (dict "service" .Values.frontend) | nindent 4 }}
  selector:
    {{- include "service.common.selectors" (dict "service" .Values.frontend) | nindent 4 }}
