apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ .Values.gateway.name }}-config
data:
  application.properties: |
    gateway.backend.url=http://backend
    server.shutdown=graceful
    management.endpoints.web.exposure.include=*
    {{ if .Values.gateway.applicationProperties }}
    {{- .Values.gateway.applicationProperties | nindent 4 }}
    {{ end }}
