apiVersion: v1
kind: Service
metadata:
  {{- include "service.common.metadata" (dict "service" .Values.gateway) | nindent 2 }}
  {{- if .Values.gateway.svc.annotations }}
  annotations:
    {{- range $key, $value := .Values.gateway.svc.annotations }}
    {{ $key }}: {{ $value }}
    {{- end }}
  {{- end }}
spec:
  ports:
    - name: http
      port: 80
      targetPort: http
  selector:
    {{- include "service.common.selectors" (dict "service" .Values.gateway) | nindent 4 }}
  {{- range $key, $value := .Values.gateway.svc.spec }}
  {{ $key }}: {{ $value }}
  {{- end }}
