apiVersion: v1
kind: ServiceAccount
metadata:
  name: orchestrator-sa

---

apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: jobs-executor
rules:
  - apiGroups: [batch]
    resources: [jobs]
    verbs: ["get", "list", "watch", "create", "update", "patch", "delete"]
  - apiGroups: [""]  # "" indicates the core API group
    resources: [pods]
    verbs: [list, get, delete, create]
  # this rule is required for sprint-cloud-kubernetes-fabric8-config
  - apiGroups: [""]  # "" indicates the core API group
    resources: [configmaps, secrets]
    verbs: [list, get, watch]

---

apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: orchestrator-jobs-binding
subjects:
  - kind: ServiceAccount
    name: orchestrator-sa
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: jobs-executor
