apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ .Values.orchestrator.name }}-config
data:
  application.properties: |
    orchestrator.backendUrl=http://backend:5000/internal
    # todo: actually use ${status.hostIP} # https://github.com/kubernetes/kubernetes/issues/107079#issuecomment-996405755
    orchestrator.docker.host=tcp://host.minikube.internal:2375
    orchestrator.docker.runtime=runc
    server.shutdown=graceful
    management.endpoints.web.exposure.include=*
