apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ .Values.orchestrator.name }}-config
data:
  application.properties: |
    orchestrator.backendUrl=http://backend:5800/internal
    orchestrator.docker.host=tcp://${HOST_IP}:2375
    orchestrator.docker.runtime=runc
    orchestrator.docker.loggingDriver=json
    server.shutdown=graceful
    management.endpoints.web.exposure.include=*
