apiVersion: v1
kind: ServiceAccount
metadata:
  name: orchestrator-sa

---

apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: jobs-executor
rules:
  - apiGroups: [batch]
    resources: [jobs]
    verbs: ["get", "list", "watch", "create", "update", "patch", "delete"]
  - apiGroups: [""]  # "" indicates the core API group
    resources: [pods, persistentvolumeclaims]
    verbs: [list, get, delete, create]

---

apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: orchestrator-jobs-binding
subjects:
  - kind: ServiceAccount
    name: orchestrator-sa
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: jobs-executor

---

apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: jobs-executor
rules:
  - apiGroups: [""]  # "" indicates the core API group
    resources: [persistentvolumes]
    verbs: [list, get, delete, create]

---

apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: orchestrator-jobs-binding
subjects:
  - kind: ServiceAccount
    name: orchestrator-sa
    namespace: {{ .Release.Namespace }}
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: jobs-executor
