apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ .Values.orchestrator.name }}-config
data:
  application.properties: |
    orchestrator.backendUrl=http://backend:5800/internal
    orchestrator.docker.host=tcp://${HOST_IP}:2375
    orchestrator.docker.runtime=runc
    orchestrator.docker.loggingDriver=json
    server.shutdown=graceful
    management.endpoints.web.exposure.include=*
    {{- if .Values.orchestrator.clusterIP }}
    orchestrator.agentSettings.orchestratorUrl=http://{{ .Values.orchestrator.clusterIP }}:{{ .Values.orchestrator.containerPort }}
    {{- end }}
    {{- if .Values.backend.clusterIP }}
    orchestrator.agentSettings.backendUrl=http://{{ .Values.backend.clusterIP }}:{{ .Values.backend.containerPort }}
    {{- end }}
