apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ .Values.orchestrator.name }}-config
data:
  application.properties: |
    orchestrator.backendUrl=http://backend/internal
    orchestrator.docker.host={{ .Values.orchestrator.dockerHost }}
    orchestrator.docker.runtime=
    orchestrator.docker.loggingDriver=json

    orchestrator.kubernetes.apiServerUrl=http://kubernetes.default.svc
    orchestrator.kubernetes.serviceAccount=${POD_SERVICE_ACCOUNT}
    orchestrator.kubernetes.namespace=${POD_NAMESPACE}

    server.shutdown=graceful
    management.endpoints.web.exposure.include=*
    orchestrator.agentSettings.orchestratorUrl=http://{{ .Values.orchestrator.name }}
    orchestrator.agentSettings.backendUrl=http://{{ .Values.backend.name }}
