apiVersion: apps/v1
kind: Deployment
metadata:
  name: preprocessor
  labels:
    {{- include "common.labels" (merge (dict "service" .Values.preprocessor) .) | nindent 4 }}
spec:
  selector:
    matchLabels:
      io.kompose.service: preprocessor
  template:
    metadata:
      labels:
        io.kompose.service: preprocessor
    spec:
      restartPolicy: Always
      {{- include "spring-boot.securityContext" . | nindent 6 }}
      containers:
        - name: preprocessor
          {{- include "spring-boot.common" (merge (dict "service" .Values.preprocessor) .) | nindent 10 }}
          volumeMounts:
            - {{ include "spring-boot.config-volume-mount" . | indent 14 | trim }}
            - name: repos-storage
              mountPath: /home/cnb
          {{- include "spring-boot.management" .Values.preprocessor | nindent 10 }}
      volumes:
        - {{ include "spring-boot.config-volume" (dict "service" .Values.preprocessor) | indent 10 | trim }}
        - name: repos-storage
          persistentVolumeClaim:
            claimName: repos-storage
