apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ .Values.preprocessor.name }}-config
data:
  application.properties: |
    {{ if .Values.preprocessor.applicationProperties }}
    {{- .Values.preprocessor.applicationProperties | nindent 4 }}
    {{ end }}
