apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  labels:
    io.kompose.service: repos-storage
  name: repos-storage
spec:
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: {{ .Values.reposStorage.size }}
