{{- if not .Values.s3.external -}}

apiVersion: v1
kind: Secret
metadata:
  name: s3-secrets
stringData:
  s3-storage.endpoint: {{ .Values.s3.endpoint | quote }}
  s3-storage.bucketName: {{ .Values.s3.bucket_name | quote }}
  s3-storage.credentials.accessKeyId: {{ .Values.s3.secret_user | quote }}
  s3-storage.credentials.secretAccessKey: {{ .Values.s3.secret_pwd | quote }}

---

apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: minio-pvc
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 3Gi
---

apiVersion: apps/v1
kind: Deployment
metadata:
  name: s3
  annotations:
    io.kompose.service: s3
spec:
  replicas: 1
  selector:
    matchLabels:
      io.kompose.service: s3
  template:
    metadata:
      labels:
        io.kompose.service: s3
    spec:
      containers:
        - image: minio/minio:latest
          name: minio
          args:
            - server
            - /data
            - --console-address
            - {{ .Values.s3.ui_port | print ":" | quote }}
          ports:
            - containerPort: {{ .Values.s3.api_port }}
              name: minio
            - containerPort: {{ .Values.s3.ui_port }}
              name: minio-ui
          env:
            - name: MINIO_ROOT_USER
              value: {{ .Values.s3.secret_user | quote }}
            - name: MINIO_ROOT_PASSWORD
              value: {{ .Values.s3.secret_pwd | quote }}
          volumeMounts:
            - mountPath: /data
              name: minio-persistent-storage
      volumes:
        - name: minio-persistent-storage
          persistentVolumeClaim:
            claimName: minio-pvc

---

# This job is required for minio bucket creation
# initContainer is not suitable for that as when it configurating the minio,
# minio container is not yet available so no configuration happens

apiVersion: batch/v1
kind: Job
metadata:
  name: minio-create-bucket
spec:
  completions: 1
  ttlSecondsAfterFinished: 10
  template:
    metadata:
      name: minio-create-bucket
    spec:
      containers:
        - name: minio-bucket
          image: minio/mc
          command:
            - /bin/sh
          args:
            - -c
            - |
              sleep 30
              /usr/bin/mc alias set minio {{ .Values.s3.endpoint }} {{ .Values.s3.secret_user }} {{ .Values.s3.secret_pwd }}
              /usr/bin/mc mb --ignore-existing minio/{{ .Values.s3.bucket_name }}
              /usr/bin/mc policy set public minio/{{ .Values.s3.bucket_name }}
              /usr/bin/mc anonymous set public minio/{{ .Values.s3.bucket_name }}
      restartPolicy: OnFailure
  backoffLimit: 5

{{ end }}