{{- if not .Values.s3.external -}}

# in order to access web ui, need to use command:
# minikube service s3-service-ui -n save-cloud --url
# where -n save-cloud  --  setting a namespace

apiVersion: v1
kind: Service
metadata:
  name: s3-service-ui
spec:
  selector:
    io.kompose.service: s3
  ports:
    - port: {{ .Values.s3.ui_port }}
      protocol: TCP
      name: s3-ui
  type: LoadBalancer

---

apiVersion: v1
kind: Service
metadata:
  name: s3
spec:
  selector:
    io.kompose.service: s3
  ports:
    - port: 80
      targetPort: {{ .Values.s3.api_port }}
      protocol: TCP
      name: s3
  type: ClusterIP

---

apiVersion: v1
kind: Service
metadata:
  name: s3-service-api
spec:
  selector:
    io.kompose.service: s3
  ports:
    - port: {{ .Values.s3.api_port }}
      protocol: TCP
      name: s3-api
  type: LoadBalancer

{{- end }}