{{- if .Values.s3.external -}}
apiVersion: v1
kind: Endpoints
metadata:
  name: s3-service
subsets:
  - addresses:
      - ip: {{ .Values.s3.ip }}
    ports:
      - port: 9000

---

apiVersion: v1
kind: Service
metadata:
  name: s3-service
spec:
  ports:
    - port: 9000
      targetPort: 9000
      protocol: TCP
  selector: {}
  type: ClusterIP

{{- end }}