apiVersion: v1
kind: ServiceAccount
metadata:
  name: sandbox-sa

---

apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: sandbox-jobs-binding
subjects:
  - kind: ServiceAccount
    name: sandbox-sa
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: jobs-executor
