{{- if .Values.sandbox_mysql.external -}}
apiVersion: v1
kind: Endpoints
metadata:
  name: sandbox-mysql-service
subsets:
  - addresses:
      - ip: {{ .Values.sandbox_mysql.ip }}
    ports:
      - port: 3306

---

apiVersion: v1
kind: Service
metadata:
  name: sandbox-mysql-service
spec:
  ports:
    - port: 3306
      targetPort: 3306
      protocol: TCP
  selector: {}
  type: ClusterIP

{{- else }}

apiVersion: v1
kind: Service
metadata:
  name: sandbox-mysql-service
spec:
  ports:
    - port: 3306
  selector:
    io.kompose.service: mysql
  clusterIP: None
{{- end }}