apiVersion: v1
kind: ServiceAccount
metadata:
  name: microservice-sa

---

# https://docs.spring.io/spring-cloud-kubernetes/docs/current/reference/html/#service-account
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: microservice
rules:
  - apiGroups: [""]  # "" indicates the core API group
    resources: [configmaps, secrets]
    verbs: [list, get, watch]

---

apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: microservice-role-binding
subjects:
  - kind: ServiceAccount
    name: microservice-sa
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: microservice

---

apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: microservice
rules:
  - apiGroups: ["authentication.k8s.io"]
    resources: [tokenreviews]
    verbs: ["create"]

---

apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: microservice-role-binding
subjects:
  - kind: ServiceAccount
    name: microservice-sa
    namespace: {{ .Release.Namespace }}
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: microservice