server:
  port: 5300
gateway:
  backend:
    url: http://backend:5000
management:
  endpoints:
    web:
      exposure:
        include: health,info,prometheus,gateway
spring:
  profiles:
    default: dev
  cloud:
    gateway:
      routes:
        - id: api_route
          uri: http://backend:5000
          predicates:
            - Path=/api/**
          filters:
            - StripPrefix=1
            # If SESSION cookie is passed to downstream, it is then removed, because downstream discards it
            - RemoveRequestHeader=Cookie
            - TokenRelay=
        - id: index_route
          uri: http://backend:5000/index.html
          predicates:
            - Path=/
          filters:
            # If SESSION cookie is passed to downstream, it is then removed, because downstream discards it
            - RemoveRequestHeader=Cookie
        - id: resource_route
          uri: http://backend:5000
          predicates:
            - Path=/*.html,/*.js*,/img/**,/*.gif,/*.svg
          filters:
            # If SESSION cookie is passed to downstream, it is then removed, because downstream discards it
            - RemoveRequestHeader=Cookie
        - id: grafana
          uri: http://grafana:9100
          predicates:
            - Path=/grafana/**