apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    io.kompose.service: backend
    prometheus-job: save-backend
  name: backend
spec:
  selector:
    matchLabels:
      io.kompose.service: backend
  template:
    metadata:
      labels:
        io.kompose.service: backend
    spec:
      containers:
        - env:
            - name: SPRING_PROFILES_ACTIVE
              value: {{ .Values.profile }}
          image: '{{ .Values.imageRegistry }}/save-backend:{{ .Values.dockerTag }}'
          name: backend
          ports:
            - containerPort: {{ .Values.backend.containerPort }}
          volumeMounts:
            - name: config-volume
              mountPath: /home/cnb/config
            - name: fs-storage
              mountPath: /home/cnb/files
            - name: database-secret
              # https://github.com/kubernetes/kubernetes/issues/65835#issuecomment-411399356
              # should un-hardcode path to secrets from env postprocessor
              mountPath: /home/cnb/secrets
          {{- include "deployment.props" .Values.backend | nindent 10 }}
      volumes:
      - name: config-volume
        configMap:
          name: backend-config
      - name: fs-storage
        persistentVolumeClaim:
          claimName: save-fs-storage
      - name: database-secret
        secret:
          secretName: db-secrets
      restartPolicy: Always
