apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    io.kompose.service: backend
    prometheus-job: save-backend
  name: backend
spec:
  selector:
    matchLabels:
      io.kompose.service: backend
  template:
    metadata:
      labels:
        io.kompose.service: backend
    spec:
      containers:
        - env:
            - name: SPRING_PROFILES_ACTIVE
              value: {{ .Values.profile }}
          image: '{{ .Values.imageRegistry }}/save-backend:{{ .Values.dockerTag }}'
          name: backend
          ports:
            - containerPort: 5000
          volumeMounts:
            - name: config-volume
              mountPath: /home/cnb/config
          livenessProbe:
            httpGet:
              path: /actuator/health/liveness
              port: 5000
          readinessProbe:
            httpGet:
              path: /actuator/health/readiness
              port: 5000
          lifecycle:
            preStop:
              exec:
                # wait till spring finishes gracefully with `server.shutdown=graceful`
                command: ["sh", "-c", "'sleep 10'"]
      volumes:
        - name: config-volume
          configMap:
            name: backend-config
      restartPolicy: Always
