apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    io.kompose.service: backend
    prometheus-job: save-backend
  name: backend
spec:
  selector:
    matchLabels:
      io.kompose.service: backend
  template:
    metadata:
      labels:
        io.kompose.service: backend
    spec:
      restartPolicy: Always
      containers:
        - name: backend
          {{- include "spring-boot.common" (merge (dict "service" .Values.backend) .) | nindent 10 }}
          volumeMounts:
            - name: fs-storage
              mountPath: /home/cnb/files
            - name: database-secret
              # https://github.com/kubernetes/kubernetes/issues/65835#issuecomment-411399356
              # should un-hardcode path to secrets from env postprocessor
              mountPath: /home/cnb/secrets
          {{- include "spring-boot.management" .Values.backend | nindent 10 }}
      volumes:
        - {{- include "spring-boot.config-volume" (dict "service" .Values.backend) | indent 10 }}
        - name: fs-storage
          persistentVolumeClaim:
            claimName: save-fs-storage
        - name: database-secret
          secret:
            secretName: db-secrets
