apiVersion: v1
kind: Service
metadata:
  name: mysql-service
spec:
  clusterIP: None
  ports:
    - port: 3306
      targetPort: 3306
  selector:
    name: mysql-service
  type: ClusterIP

---

apiVersion: v1
kind: Endpoints
metadata:
  name: mysql-endpoint
subsets:
  - addresses:
      - ip: {{ .Values.mysql.ip }}
    ports:
      - port: 3306