apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  labels:
    io.kompose.service: save-fs-storage
  name: save-fs-storage
spec:
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: {{ .Values.storage.size }}
