apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    io.kompose.service: gateway
    prometheus-job: api-gateway
  name: gateway
spec:
  selector:
    matchLabels:
      io.kompose.service: gateway
  template:
    metadata:
      labels:
        io.kompose.service: gateway
    spec:
      containers:
        - env:
            - name: SPRING_PROFILES_ACTIVE
              value: {{ .Values.profile }}
          image: '{{ .Values.imageRegistry }}/api-gateway:{{ .Values.dockerTag }}'
          name: gateway
          ports:
            - containerPort: 5300
          volumeMounts:
            - name: config-volume
              mountPath: /home/cnb/config
          livenessProbe:
            httpGet:
              path: /actuator/health/liveness
              port: 5300
          readinessProbe:
            httpGet:
              path: /actuator/health/readiness
              port: 5300
          lifecycle:
            preStop:
              exec:
                # wait till spring finishes gracefully with `server.shutdown=graceful`
                command: ["sh", "-c", "'sleep 10'"]
      volumes:
        - name: config-volume
          configMap:
            name: gateway-config
            items:
              - key: application.properties
                path: application.properties
      restartPolicy: Always
