apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    io.kompose.service: gateway
    prometheus-job: api-gateway
  name: gateway
spec:
  selector:
    matchLabels:
      io.kompose.service: gateway
  template:
    metadata:
      labels:
        io.kompose.service: gateway
    spec:
      restartPolicy: Always
      containers:
        - name: gateway
          {{- include "spring-boot.common" (merge (dict "service" .Values.gateway) .) | nindent 10 }}
          {{- include "spring-boot.management" .Values.gateway | nindent 10 }}
      volumes:
        - {{- include "spring-boot.config-volume" (dict "service" .Values.gateway) | indent 10 }}
