imageRegistry: ghcr.io/analysis-dev
# todo: version from git tag
dockerTag: 0.2.0-alpha.0.250-6d8ca62

env: staging
# todo: set profiles per service
profile: dev,secure
backend:
  name: backend
  imageName: save-backend
  containerPort: 5000
orchestrator:
  name: orchestrator
  imageName: save-orchestrator
  containerPort: 5100
preprocessor:
  name: preprocessor
  imageName: save-preprocessor
  containerPort: 5200
gateway:
  name: gateway
  imageName: api-gateway
  containerPort: 5300
storage:
  size: 10Gi
reposStorage:
  size: 2Gi
mysql:
  # this is resolved IP of host.minikube.internal
  ip: 192.168.65.2

grafana:
  image:
    tag: 8.4.4
  service:
    port: 9100
  persistence:
    enabled: true
  rbac:
    create: false
