scrape_configs:
  # Make Prometheus scrape itself for metrics.
  - job_name: 'prometheus'
    static_configs:
      - targets: ['localhost:9090']
  - job_name: 'node-exporter'
    static_configs:
      - targets: ['host.docker.internal:9091']

  # Create a job for Docker Swarm containers.
  - job_name: 'dockerswarm'
    metrics_path: '/actuator/prometheus'
    dockerswarm_sd_configs:
      - host: unix:///var/run/docker.sock
        role: tasks
    relabel_configs:
      # Only keep containers that should be running.
      - source_labels: [__meta_dockerswarm_task_desired_state]
        regex: running
        action: keep
      # Only keep containers that have a `prometheus-job` label.
      - source_labels: [__meta_dockerswarm_service_label_prometheus_job]
        regex: .+
        action: keep
      # Use the prometheus-job Swarm label as Prometheus job label.
      - source_labels: [__meta_dockerswarm_service_label_prometheus_job]
        target_label: job
      # Adding docker_node label to the targets
      - source_labels: [ __meta_dockerswarm_node_hostname ]
        target_label: docker_node
  - job_name: 'dockerswarm-api_gateway'
    metrics_path: '/actuator/prometheus'
    dockerswarm_sd_configs:
      - host: unix:///var/run/docker.sock
        role: tasks
        filters:
        - name: name
          values: ['save_gateway']
    basic_auth:
      username: prometheus
      password_file: /run/secrets/prometheus_scrape_pwd
    relabel_configs:
      # Only keep containers that should be running.
      - source_labels: [__meta_dockerswarm_task_desired_state]
        regex: running
        action: keep
      # Only keep containers that have a `prometheus-job` label.
      - source_labels: [__meta_dockerswarm_service_label_prometheus_job]
        regex: .+
        action: keep
      # Use the prometheus-job Swarm label as Prometheus job label.
      - source_labels: [__meta_dockerswarm_service_label_prometheus_job]
        target_label: job
      # Adding docker_node label to the targets
      - source_labels: [ __meta_dockerswarm_node_hostname ]
        target_label: docker_node
