apiVersion: v1
name: save-cloud
description: Helm chart for SAVE Cloud service
# todo: separate versioning of charts or aligned with project version?
version: 0.1.0
sources:
  - https://github.com/saveourtool/save-cloud
  - https://github.com/saveourtool/save-cli
