imageRegistry: ghcr.io/saveourtool
# dockerTag: <TDB>  # this should be set explicitly during chart installation

env: staging
# Unless overridden, this will be set as Spring profile of a component.
profile: dev
pullPolicy: IfNotPresent
ingress:
  enabled: false
  https:
    enabled: false
backend:
  name: backend
  profile: dev,secure,kubernetes
  imageName: save-backend
  containerPort: 5800
  managementPort: 5801
  # Fixed ClusterIP can be assigned to make it easier to query backend from services outside Kubernetes.
  # Should be chosen depending on cluster's network configuration: https://kubernetes.io/docs/concepts/services-networking/service/#choosing-your-own-ip-address.
  clusterIP: null
frontend:
  name: frontend
  imageName: save-frontend
  containerPort: 5810
orchestrator:
  name: orchestrator
  imageName: save-orchestrator
  containerPort: 5100
  managementPort: 5101
  # Fixed ClusterIP can be assigned to make it easier to query orchestrator from services outside Kubernetes
  clusterIP: null
  dockerHost: tcp://${HOST_IP}:2375
sandbox:
  name: sandbox
  profile: dev,secure
  imageName: save-sandbox
  containerPort: 5400
  managementPort: 5401
  # Fixed ClusterIP can be assigned to make it easier to query orchestrator from services outside Kubernetes
  clusterIP: null
  dockerHost: tcp://${HOST_IP}:2375
preprocessor:
  name: preprocessor
  imageName: save-preprocessor
  containerPort: 5200
  managementPort: 5201
  # Fixed ClusterIP can be assigned to make it easier to query preprocessor from services outside Kubernetes
  clusterIP: null
gateway:
  name: gateway
  profile: dev,kubernetes
  imageName: api-gateway
  containerPort: 5300
  managementPort: 5301
  # Additional properties for `application.properties` file that will be mounted as an optional property source.
  applicationProperties:
  svc:
    annotations: {}
    # Any additional options for Service `spec` block
    spec: {}
s3:
  external: true
  secretFile: /home/cnb/secrets/s3_secrets
storage:
  size: 10Gi
reposStorage:
  size: 2Gi
logsStorage:
  size: 2Gi
mysql:
  # If true, a Service will be created to enable communication with an external DB by its IP.
  # If false, a Deployment will be created for a MySQL pod.
  external: true
  # IP address of an external MySQL database.
  # As an example, this is what may be a resolved IP of `host.minikube.internal`.
  ip: 192.168.65.2
  # Name of the database schema that will be used by save-cloud deployment
  backend_schema: save_cloud
  sandbox_schema: save_sandbox
  demo_schema: save_demo
  root_password: '123'
  migrations:
    # Whether database migrations should be executed while deploying the application
    enabled: false
  dbPasswordFile: /home/cnb/secrets/db_secrets

# Values for dependencies
grafana:
  enabled: false
  image:
    repository: grafana/grafana
    tag: 9.3.6
  deploymentStrategy:
    # If we have a single replica of Grafana and PV doesn't support MultiAttach, then `RollingUpdate` will fail.
    type: Recreate
  service:
    port: 9100
  persistence:
    enabled: true
  rbac:
    create: false

prometheus:
  enabled: false
  alertmanager:
    enabled: false
  kube-state-metrics:
    enabled: false
  configmapReload:
    prometheus:
      enabled: false
  prometheus-node-exporter:
    enabled: false
  server:
    image:
      repository: quay.io/prometheus/prometheus
      tag: v2.42.0
    strategy:
      # If we have a single replica of Prometheus and PV doesn't support MultiAttach, then `RollingUpdate` will fail.
      type: Recreate
  prometheus-pushgateway:
    enabled: false

promtail:
  image:
    repository: grafana/promtail
    tag: 2.7.3
  podLabels:
    # This label will make promtail scrape itself according to the pipeeline stages below.
    io.kompose.service: promtail
  config:
    clients:
      - url: http://loki:3100/loki/api/v1/push
    snippets:
      pipelineStages:
        - cri: {}
        - output:
            source: output
        - labels:
            stream:
        - multiline:
            firstline: '^\d{2}:\d{2}:\d{2}\.\d{3} \[(?P<thread>[\w\d\-.]+)\] (?P<level>\w+)'
        - regex:
            expression: '^\d{2}:\d{2}:\d{2}\.\d{3} \[(?P<thread>[\w\d\-.]+)\] (?P<level>\w+)'
        - labels:
            level:
      extraRelabelConfigs:
        - action: keep
          regex: .*true.*
          source_labels:
            - __meta_kubernetes_pod_labelpresent_io_kompose_service
            - __meta_kubernetes_pod_labelpresent_executionId
loki:
  enabled: false
  # For compatibility with PV created in v2; see https://github.com/grafana/loki/issues/7267#issuecomment-1264472870
  # for a more comprehensive list.
  fullnameOverride: save-cloud-loki
  gateway:
    enabled: false
  ingress:
    # See https://github.com/grafana/loki/issues/7318
    paths:
      headless:
        - /
      read:
      write:
  loki:
    image:
      repository: grafana/loki
      tag: 2.7.3
    auth_enabled: false
    commonConfig:
      replication_factor: 1
    structuredConfig:
      ingester:
        # https://grafana.com/docs/loki/latest/operations/storage/filesystem/
        max_chunk_age: 2h
        chunk_idle_period: 2h
    storage:
      type: 'filesystem'
    rulerConfig:
      storage:
        type: 'local'
  singleBinary:

neo4j:
  enabled: true
  ingress:
    enabled: false
  svc:
    annotations: {}
    # Any additional options for Service `spec` block
    spec: {}
  neo4j:
    edition: community
    name: simple-neo4j
    resources:
      cpu: "500m"
      memory: "2Gi"
  volumes:
    data:
      mode: selector
      selector:

demo_cpg:
  name: demo-cpg
  profile: dev
  imageName: save-demo-cpg
  containerPort: 5500
  managementPort: 5501
  clusterIP: null
demo:
  name: demo
  profile: dev
  imageName: save-demo
  containerPort: 5421
  managementPort: 5422
  clusterIP: null
