# values specific to deployment into Minikube

profile: dev
backend:
  profile: dev,secure,kubernetes
gateway:
  profile: dev,kubernetes
  applicationProperties: |+
    server.shutdown=graceful
    management.endpoints.web.exposure.include=*
    gateway.knownActuatorConsumers=172.0.0.0/8
orchestrator:
  dockerHost: tcp://${HOST_IP}:2376
mysql:
  external: false
  ip: nil

# dependencies
