# values specific to deployment into Minikube

profile: dev
ingress:
  enabled: false
backend:
  profile: dev,secure,kubernetes
gateway:
  profile: dev,kubernetes
  applicationProperties: |+
    server.shutdown=graceful
    management.endpoints.web.exposure.include=*
    gateway.knownActuatorConsumers=172.0.0.0/8
orchestrator:
  profile: dev,kubernetes,minikube
  dockerHost: tcp://${HOST_IP}:2376
  applicationProperties: |
    orchestrator.agents-count=1
    logging.level.com.saveourtool=DEBUG
    orchestrator.kubernetes.useGvisor=false
sandbox:
  profile: dev,kubernetes,minikube
  dockerHost: tcp://${HOST_IP}:2376
  applicationProperties: |
    orchestrator.docker.host=tcp://localhost:2376
    logging.level.com.saveourtool=DEBUG
    orchestrator.kubernetes.useGvisor=false
demo_cpg:
  profile: dev
demo:
  profile: dev
  dockerHost: tcp://${HOST_IP}:2376
  applicationProperties: |
    demo.kubernetes.useGvisor=false

mysql:
  external: false
  ip: nil
  migrations:
    enabled: false
s3:
  external: false
  secret_user: admin
  secret_pwd: adminadmin
  bucket_name: cnb
  api_port: 9000
  ui_port: 9090
  endpoint: http://s3

# dependencies
