name: Build and test

on:
  pull_request:
  push:
    branches:
      - 'master'

concurrency:
  # https://docs.github.com/en/actions/using-jobs/using-concurrency
  # The latest queued workflow is preferred; the ones already in progress get cancelled
  # Workflows on master branch shouldn't be cancelled, that's why they are identified by commit SHA
  group: ${{ github.ref == 'refs/heads/master' && format('{0}-{1}', github.workflow, github.sha) || format('{0}-{1}', github.workflow, github.ref) }}
  cancel-in-progress: true

jobs:
  build_save-cloud-common:
    name: Build, test and upload code coverage (save-cloud-common)
    uses: ./.github/workflows/reusable_build_and_test.yml
    with:
      module: save-cloud-common
  build_save-orchestrator-common:
    name: Build, test and upload code coverage (save-orchestrator-common)
    needs: [ build_save-cloud-common ]
    uses: ./.github/workflows/reusable_build_and_test.yml
    with:
      module: save-orchestrator-common
  build_all:
    name: Build, test and upload code coverage by module
    needs: [ build_save-cloud-common, build_save-orchestrator-common ]
    strategy:
      fail-fast: false
      matrix:
        module: [
          'api-gateway',
          'save-backend',
          'save-orchestrator',
          'save-frontend',
          'save-agent',
          'save-preprocessor',
          'test-utils',
          'save-api',
          'save-api-cli',
          'save-sandbox',
          'authentication-service',
          'save-demo',
          'save-demo-cpg',
          'test-analysis-core',
          'save-demo-agent'
        ]
    uses: ./.github/workflows/reusable_build_and_test.yml
    with:
      module: ${{ matrix.module }}

  build_and_test_with_code_coverage:
    name: Build, test and upload code coverage
    needs: [ build_save-cloud-common, build_save-orchestrator-common, build_all ]
    runs-on: ubuntu-latest
    steps:
      - name: Download gradle reports (api-gateway)
        uses: actions/download-artifact@v3
        with:
          name: gradle-reports-api-gateway

      - name: Download gradle reports (save-backend)
        uses: actions/download-artifact@v3
        with:
          name: gradle-reports-save-backend

      - name: Download gradle reports (save-orchestrator-common)
        uses: actions/download-artifact@v3
        with:
          name: gradle-reports-save-orchestrator-common

      - name: Download gradle reports (save-orchestrator)
        uses: actions/download-artifact@v3
        with:
          name: gradle-reports-save-orchestrator

      - name: Download gradle reports (save-frontend)
        uses: actions/download-artifact@v3
        with:
          name: gradle-reports-save-frontend

      - name: Download gradle reports (save-cloud-common)
        uses: actions/download-artifact@v3
        with:
          name: gradle-reports-save-cloud-common

      - name: Download gradle reports (save-agent)
        uses: actions/download-artifact@v3
        with:
          name: gradle-reports-save-agent

      - name: Download gradle reports (save-preprocessor)
        uses: actions/download-artifact@v3
        with:
          name: gradle-reports-save-preprocessor

      - name: Download gradle reports (test-utils)
        uses: actions/download-artifact@v3
        with:
          name: gradle-reports-test-utils

      - name: Download gradle reports (save-api)
        uses: actions/download-artifact@v3
        with:
          name: gradle-reports-save-api

      - name: Download gradle reports (save-api-cli)
        uses: actions/download-artifact@v3
        with:
          name: gradle-reports-save-api-cli

      - name: Download gradle reports (save-sandbox)
        uses: actions/download-artifact@v3
        with:
          name: gradle-reports-save-sandbox

      - name: Download gradle reports (authentication-service)
        uses: actions/download-artifact@v3
        with:
          name: gradle-reports-authentication-service

      - name: Download gradle reports (save-demo)
        uses: actions/download-artifact@v3
        with:
          name: gradle-reports-save-demo

      - name: Download gradle reports (save-demo-cpg)
        uses: actions/download-artifact@v3
        with:
          name: gradle-reports-save-demo-cpg

      - name: Download gradle reports (test-analysis-core)
        uses: actions/download-artifact@v3
        with:
          name: gradle-reports-test-analysis-core

      - name: Download gradle reports (save-demo-agent)
        uses: actions/download-artifact@v3
        with:
          name: gradle-reports-save-demo-agent

      - name: Code coverage report
        uses: codecov/codecov-action@v3
        with:
          fail_ci_if_error: false
