name: Build base images for SAVE execution

on:
  schedule:
    - cron: '0 4 * * 1'
  workflow_dispatch:
  # Fixme: only for testing
  push:

jobs:
  build_base_images:
    name: Build base images and push to ghcr.io
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        # This should replicate list of SDKs from com.saveourtool.save.domain.Sdk
        include:
          - base_image_name: openjdk
            base_image_tag: 8
          - base_image_name: openjdk
            base_image_tag: 9
          - base_image_name: openjdk
            base_image_tag: 10
          - base_image_name: openjdk
            base_image_tag: 11
          - base_image_name: openjdk
            base_image_tag: 12
          - base_image_name: openjdk
            base_image_tag: 13
          - base_image_name: openjdk
            base_image_tag: 14
          - base_image_name: openjdk
            base_image_tag: 15
          - base_image_name: openjdk
            base_image_tag: 16
          - base_image_name: openjdk
            base_image_tag: 17
          - base_image_name: python
            base_image_tag: 2.7
          - base_image_name: python
            base_image_tag: 3.2
          - base_image_name: python
            base_image_tag: 3.3
          - base_image_name: python
            base_image_tag: 3.4
          - base_image_name: python
            base_image_tag: 3.5
          - base_image_name: python
            base_image_tag: 3.6
          - base_image_name: python
            base_image_tag: 3.7
          - base_image_name: python
            base_image_tag: 3.8
          - base_image_name: python
            base_image_tag: 3.9
          - base_image_name: python
            base_image_tag: 3.10
    steps:
      - uses: actions/checkout@v3
      - uses: docker/login-action@v2
        with:
          registry: ghcr.io
          username: saveourtool
          password: ${{ secrets.GITHUB_TOKEN }}
      - uses: docker/build-push-action@v3
        with:
          context: save-deploy/base-images
          push: true
          # https://github.com/marketplace/actions/build-and-push-docker-images#inputs
          # '`List` type is a newline-delimited string'
          build-args: |
            BASE_IMAGE_NAME=${{ matrix.base_image_name }}
            BASE_IMAGE_TAG=${{ matrix.base_image_tag }}
          tags: ghcr.io/saveourtool/save-base:${{ matrix.base_image_name }}-${{ matrix.base_image_tag }}
