name: Build and test

on:
  pull_request:
  push:
    branches:
      - 'master'

jobs:
  build_and_test_with_code_coverage:
    name: Build, test and upload code coverage
    runs-on: ubuntu-20.04

    steps:
      - uses: actions/checkout@v2.4.0
        with:
          # required for correct codecov upload
          fetch-depth: 0
      - name: Set up JDK 11
        uses: actions/setup-java@v2
        with:
          java-version: 11
          distribution: zulu
      - name: Install system packages
        # libcurl is needed for ktor-client-curl, libc-bin for orchestrator
        run: sudo apt-get update && sudo apt-get install -y libcurl4-openssl-dev libc-bin
      - name: Cache konan
        uses: actions/cache@v2
        with:
          path: ~/.konan
          key: ${{ runner.os }}-gradle-konan
          restore-keys: |
            ${{ runner.os }}-gradle-konan
      # https://gvisor.dev/docs/user_guide/install/
      - name: Install gvisor runsc runtime
        run: |
          ARCH=$(uname -m)
          URL=https://storage.googleapis.com/gvisor/releases/release/latest/${ARCH}
          wget -nv ${URL}/runsc ${URL}/runsc.sha512 \
            ${URL}/containerd-shim-runsc-v1 ${URL}/containerd-shim-runsc-v1.sha512
          sha512sum -c runsc.sha512 \
            -c containerd-shim-runsc-v1.sha512
          rm -f *.sha512
          chmod a+rx runsc containerd-shim-runsc-v1
          sudo mv runsc containerd-shim-runsc-v1 /usr/local/bin
          sudo /usr/local/bin/runsc install
          sudo systemctl reload docker
      - uses: burrunan/gradle-cache-action@v1
        with:
          gradle-version: wrapper
          # additional files to calculate key for dependency cache
          gradle-dependencies-cache-key: |
            buildSrc/**/Versions.kt
          arguments: |
            build
            -x detekt
            -x :save-agent:linkDebugExecutableLinuxX64
          properties: |
            org.gradle.caching=true
            detekt.multiplatform.disabled=true

      - name: Upload gradle reports
        if: ${{ always() }}
        uses: actions/upload-artifact@v2
        with:
          name: gradle-reports
          path: '**/build/reports/'
          retention-days: 1
      - name: Upload frontend distribution
        uses: actions/upload-artifact@v2
        with:
          name: save-frontend
          path: 'save-frontend/build/libs/save-frontend-*-distribution.jar'
          retention-days: 1
      - name: Code coverage report
        run: bash <(curl -s https://codecov.io/bash)
