name: Test Helm charts

on:
  pull_request:
    paths:
      - 'save-cloud-charts/**'

jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      # https://github.com/helm/chart-testing#local-repo
      - uses: pozetroninc/github-action-get-latest-release@master
        id: ct-version
        with:
          owner: helm
          repo: chart-testing
      - run: |
          docker run --network host --workdir=/data --volume ~/.kube/config:/root/.kube/config:ro --volume $(pwd)/save-cloud-charts:/data \
          quay.io/helmpack/chart-testing:${{ steps.ct-version.outputs.release }} sh -c \
          "helm repo add grafana https://grafana.github.io/helm-charts && helm repo add prometheus https://prometheus-community.github.io/helm-charts && 
          helm repo add neo4j https://helm.neo4j.com/neo4j && ct lint --validate-maintainers=false --chart-dirs /data/save-cloud --charts save-cloud"
