name: Test Helm charts

on:
  pull_request:
    paths:
      - 'save-cloud-charts/**'

jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      # https://github.com/helm/chart-testing#local-repo
      - run: |
          docker run --network host --workdir=/data --volume ~/.kube/config:/root/.kube/config:ro --volume $(pwd)/save-cloud-charts:/data \
          quay.io/helmpack/chart-testing:v3.5.1 sh -c \
          "helm repo add grafana https://grafana.github.io/helm-charts && ct lint --validate-maintainers=false --chart-dirs /data/save-cloud --charts save-cloud"
