name: Build and push Docker images

on:
  push:
    branches:
      - 'master'
    tags:
      - 'v*'
  workflow_dispatch:
    inputs:
      branch:
        type: string
        default: master
        description: Branch to build images from
        required: false
      gateway:
        type: boolean
        default: true
        description: Build new image of api-gateway
        required: false
      backend:
        type: boolean
        default: true
        description: Build new image of save-backend
        required: false
      frontend:
        type: boolean
        default: true
        description: Build new image of save-frontend
        required: false
      orchestrator:
        type: boolean
        default: true
        description: Build new image of save-orchestrator
        required: false
      sandbox:
        type: boolean
        default: true
        description: Build new image of save-sandbox
        required: false
      preprocessor:
        type: boolean
        default: true
        description: Build new image of save-preprocessor
        required: false
      demo:
        type: boolean
        default: true
        description: Build new image of save-demo
        required: false
      demo-cpg:
        type: boolean
        default: true
        description: Build new image of save-demo-cpg
        required: false

jobs:
  retrieve_save_cli_version:
    name: Retrieve save-cli version from save-cloud
    runs-on: ubuntu-latest
    outputs:
      version: ${{ steps.save-save-cli-version.outputs.version }}
    steps:
      - name: checkout save-cloud
        uses: actions/checkout@v3
      - id: save-save-cli-version
        name: Store save-cli version in env
        run: |
          sv=$(cat gradle/libs.versions.toml | grep -m1 '^save-cli =' | awk -F'[=]' '{print $2}' | tr -d '" ')
          echo version=$sv >> $GITHUB_OUTPUT

  build_cli:
    name: Build save-cli
    needs: [ retrieve_save_cli_version ]
    uses: ./.github/workflows/build_save-cli_reusable.yml
    with:
      do-build: ${{ endsWith(needs.retrieve_save_cli_version.version, '-SNAPSHOT') }}

  deploy_gateway:
    name: Build and push Docker image (api-gateway)
    uses: ./.github/workflows/deploy_images_reusable.yml
    if: github.event_name != 'workflow_dispatch' || inputs.gateway
    with:
      module: api-gateway
      branch: ${{ inputs.branch }}

  deploy_backend:
    name: Build and push Docker image (save-backend)
    uses: ./.github/workflows/deploy_images_reusable.yml
    needs: [ build_cli ]
    if: github.event_name != 'workflow_dispatch' || inputs.backend
    with:
      module: save-backend
      branch: ${{ inputs.branch }}

  deploy_frontend:
    name: Build and push Docker image (save-frontend)
    uses: ./.github/workflows/deploy_images_reusable.yml
    if: github.event_name != 'workflow_dispatch' || inputs.frontend
    with:
      module: save-frontend
      branch: ${{ inputs.branch }}

  deploy_orchestrator:
    name: Build and push Docker image (save-orchestrator)
    uses: ./.github/workflows/deploy_images_reusable.yml
    if: github.event_name != 'workflow_dispatch' || inputs.orchestrator
    with:
      module: save-orchestrator
      branch: ${{ inputs.branch }}

  deploy_sandbox:
    name: Build and push Docker image (save-sandbox)
    uses: ./.github/workflows/deploy_images_reusable.yml
    needs: [ build_cli ]
    if: github.event_name != 'workflow_dispatch' || inputs.sandbox
    with:
      module: save-sandbox
      branch: ${{ inputs.branch }}

  deploy_preprocessor:
    name: Build and push Docker image (save-preprocessor)
    uses: ./.github/workflows/deploy_images_reusable.yml
    if: github.event_name != 'workflow_dispatch' || inputs.preprocessor
    with:
      module: save-preprocessor
      branch: ${{ inputs.branch }}

  deploy_demo:
    name: Build and push Docker image (save-demo)
    uses: ./.github/workflows/deploy_images_reusable.yml
    if: github.event_name != 'workflow_dispatch' || inputs.demo
    with:
      module: save-demo
      branch: ${{ inputs.branch }}

  deploy_demo-cpg:
    name: Build and push Docker image (save-demo-cpg)
    uses: ./.github/workflows/deploy_images_reusable.yml
    if: github.event_name != 'workflow_dispatch' || inputs.demo-cpg
    with:
      module: save-demo-cpg
      branch: ${{ inputs.branch }}
