name: Run deteKT

on:
  push:
    branches: [ master ]
  pull_request:

jobs:
  detekt_check:
    runs-on: ubuntu-20.04

    steps:
      - uses: actions/checkout@v2.4.0
        with:
          submodules: true
      - name: Set up JDK 11
        uses: actions/setup-java@v2
        with:
          java-version: 11
          distribution: zulu
      - uses: gradle/gradle-build-action@v2
        with:
          gradle-version: wrapper
          arguments: |
            detektAll
      - name: Copy SARIF reports into a single directory
        if: ${{ always() }}
        run: |
          mkdir -p build/detekt-sarif-reports
          i=0
          find . -path "*/build/reports/detekt/*.sarif" | while read -r f; do echo "$f -> detekt-$i.sarif" && cp $f build/detekt-sarif-reports/detekt-$i.sarif || echo Cannot copy && echo Copied && i=$((i+1)); done
      - name: Upload SARIF to Github
        if: ${{ always() }}
        uses: github/codeql-action/upload-sarif@v1
        with:
          sarif_file: build/detekt-sarif-reports
