name: Run deteKT

on:
  push:
    branches: [ master ]
  pull_request:

jobs:
  detekt_check:
    runs-on: ubuntu-20.04
    env:
      GRADLE_OPTS: -Dorg.gradle.daemon=false

    steps:
      - uses: actions/checkout@v2.4.0
      - name: Set up JDK 11
        uses: actions/setup-java@v2
        with:
          java-version: 11
          distribution: zulu
      - uses: burrunan/gradle-cache-action@v1
        with:
          gradle-version: wrapper
          # additional files to calculate key for dependency cache
          gradle-dependencies-cache-key: |
            buildSrc/**/Versions.kt
      # Workaround for bug in gradle-cache-action + detekt
      - name: Run gradle command
        run: ./gradlew detektAll
