name: Run diKTat

on:
  push:
    branches: [ master ]
  pull_request:

jobs:
  diktat_check:
    runs-on: ubuntu-20.04
    env:
      GRADLE_OPTS: -Dorg.gradle.daemon=false

    steps:
      - uses: actions/checkout@v3
      - name: Set up JDK 11
        uses: actions/setup-java@v3
        with:
          java-version: 11
          distribution: temurin
      - uses: gradle/gradle-build-action@v2
        with:
          gradle-version: wrapper
          arguments: |
            diktatCheck
            mergeDiktatReports
            -Pdiktat.githubActions=true
            -Pdetekt.multiplatform.disabled=true
            --build-cache
            --continue
            -PgprUser=${{ github.actor }}
            -PgprKey=${{ secrets.GITHUB_TOKEN }}
      - name: Upload SARIF report to Github
        uses: github/codeql-action/upload-sarif@v2
        if: ${{ always() }}
        with:
          sarif_file: build/reports/diktat/diktat-merged.sarif
      - name: Upload SARIF artifacts
        uses: actions/upload-artifact@v3
        if: ${{ always() }}
        with:
          name: sarif-reports
          path: "**/build/diktat-sarif-reports/"
          retention-days: 1
