name: Run diKTat

on:
  push:
    branches: [ master ]
  pull_request:

jobs:
  diktat_check:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
      - name: Upload SARIF report to Github
        uses: github/codeql-action/upload-sarif@v2
        if: ${{ always() }}
        with:
          sarif_file: diktat-merged.sarif
