name: Run diKTat

on:
  push:
    branches: [ master ]
  pull_request:

jobs:
  diktat_check:
    runs-on: ubuntu-20.04
    env:
      GRADLE_OPTS: -Dorg.gradle.daemon=false

    steps:
      - uses: actions/checkout@v2.4.0
      - name: Set up JDK 11
        uses: actions/setup-java@v2
        with:
          java-version: 11
          distribution: zulu
      - uses: burrunan/gradle-cache-action@v1
        with:
          gradle-version: wrapper
          # additional files to calculate key for dependency cache
          gradle-dependencies-cache-key: |
            buildSrc/**/Versions.kt
          arguments: |
            diktatCheckAll
          properties: |
            diktat.githubActions=true
            detekt.multiplatform.disabled=true
      - name: Copy SARIF reports into a single directory
        if: ${{ always() }}
        # `find` cmd is a workaround for https://github.com/analysis-dev/diktat/issues/1213
        run: |
          mkdir -p build/diktat-sarif-reports
          i=0
          find . -regex '.*\(/[^/]*\)\1' | while read -r f; do echo "$f -> diktat-$i.sarif" && cp $f build/diktat-sarif-reports/diktat-$i.sarif || echo Cannot copy && echo Copied && i=$((i+1)); done
      - name: Upload SARIF report to Github
        uses: github/codeql-action/upload-sarif@v1
        if: ${{ always() }}
        with:
          sarif_file: build/diktat-sarif-reports
