name: Build Save-API CLI

on:
  pull_request:
    paths:
      - 'save-api/**'
      - 'save-api-cli/**'

jobs:
  build_and_test_with_code_coverage:
    name: Build, test and upload code coverage
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
      - name: Set up JDK 17
        uses: actions/setup-java@v4
        with:
          java-version: 17
          distribution: temurin
      - name: Install system packages
        # libcurl is needed for ktor-client-curl, libc-bin for orchestrator
        run: sudo apt-get update && sudo apt-get install -y libcurl4-openssl-dev libc-bin
      - name: Cache konan
        uses: actions/cache@v4
        with:
          path: ~/.konan
          key: ${{ runner.os }}-gradle-konan-1.7.0

      - uses: gradle/gradle-build-action@v3
        with:
          gradle-version: wrapper
          arguments: |
            save-api-cli:build
            -x detekt
            -x spotlessCheck
            --build-cache
            -Pdetekt.multiplatform.disabled=true
            -PgprUser=${{ github.actor }}
            -PgprKey=${{ secrets.GITHUB_TOKEN }}

      - name: Upload gradle reports
        if: ${{ always() }}
        uses: actions/upload-artifact@v4
        with:
          name: gradle-reports
          path: '**/build/reports/'
          retention-days: 1
