name: Create release

# publishToMavenLocal

on:
  push:
    branches:
      - main
    paths:
      - 'save-api/**'
      - 'save-api-cli/**'
env:
  GPG_SEC: ${{ secrets.PGP_SEC }}
  GPG_PASSWORD: ${{ secrets.PGP_PASSWORD }}
  OSSRH_USERNAME: ${{ secrets.SONATYPE_USER }}
  OSSRH_PASSWORD: ${{ secrets.SONATYPE_PASSWORD }}

jobs:
  release:
    name: Build release
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ ubuntu-latest, windows-latest, macos-latest ]
    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          # release workflow should have access to all tags
          fetch-depth: 0
      - name: Set up JDK 11
        uses: actions/setup-java@v3
        with:
          java-version: 11
          distribution: zulu
      - name: Status git before
        run: git status
      - uses: burrunan/gradle-cache-action@v1
        with:
          gradle-version: wrapper
      # Until https://github.com/burrunan/gradle-cache-action/issues/42 is addressed, gradle should be run as a separate step
      - name: gradle release from tag
        # if workflow is triggered after push of a tag, deploy full release
        if: ${{ startsWith(github.ref, 'refs/tags/') }}
        run: |
          ./gradlew --build-cache -Prelease -PgprUser=${{ github.actor }} -PgprKey=${{ secrets.GITHUB_TOKEN }} \
            linkReleaseExecutableMultiplatform publishToSonatype closeSonatypeStagingRepository
      - name: gradle snapshot from branch
        # if workflow is triggered after push to a branch, deploy snapshot
        if: ${{ startsWith(github.ref, 'refs/heads/') }}
        run: |
        ./gradlew --build-cache -Prelease -PgprUser=${{ github.actor }} -PgprKey=${{ secrets.GITHUB_TOKEN }} -Preckon.stage=snapshot \
          linkReleaseExecutableMultiplatform publishToSonatype
        shell: bash
      - name: Status git after
        if: ${{ always() }}
        run: git status
      - name: Upload artifact
        id: upload_artifact
        uses: actions/upload-artifact@v3
        with:
          name: save-api-${{ runner.os }}
          path: save-api/build/bin/**/releaseExecutable/*
          retention-days: 1
